<a href="https://colab.research.google.com/github/tmontaj/scripter/blob/main/Notebooks/ctc_decoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# inputs of shape (batch, time_stips, features)
def ctc_decoder(inputs, sequence_length=None, beam_width=10, top_paths=1):

  #if not padded
  if not sequence_length:
    sequence_length = [inputs.shape[1]]
    ishape = inputs.shape
    inputs = tf.reshape(inputs, (ishape[1], ishape[0], ishape[2]))
  else:
    inputs = tf.stack(inputs.numpy().tolist(), axis=1)

  print(inputs)
  decode = tf.nn.ctc_beam_search_decoder(inputs=inputs, sequence_length=sequence_length, beam_width=beam_width, top_paths=top_paths)

  return decode

In [ ]:
x=np.array([
            [
            [3,5,65,0],
            [3,5,65,0],
            [3,5,65,0],
            [3,5,65,0],
            ],
            [
            [3,5,50,0],
            [3,5,0,100],
            [3,500,66,5],
            [3,5,64,2],
            ]
 ], dtype=np.float32)

In [ ]:
  x.shape

(2, 4, 4)

In [ ]:
tf.stack(x.tolist(), axis=1)

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[  3.,   5.,  65.,   0.],
        [  3.,   5.,  50.,   0.]],

       [[  3.,   5.,  65.,   0.],
        [  3.,   5.,   0., 100.]],

       [[  3.,   5.,  65.,   0.],
        [  3., 500.,  66.,   5.]],

       [[  3.,   5.,  65.,   0.],
        [  3.,   5.,  64.,   2.]]], dtype=float32)>

In [ ]:
ishape = x.shape
tf.reshape(x, (ishape[1], ishape[0], ishape[2]))

<tf.Tensor: shape=(4, 2, 4), dtype=float32, numpy=
array([[[  3.,   5.,  65.,   0.],
        [  3.,   5.,  65.,   0.]],

       [[  3.,   5.,  65.,   0.],
        [  3.,   5.,  65.,   0.]],

       [[  3.,   5.,  50.,   0.],
        [  3.,   5.,   0., 100.]],

       [[  3., 500.,  66.,   5.],
        [  3.,   5.,  64.,   2.]]], dtype=float32)>

In [ ]:
y = ctc_decoder(x,sequence_length=[4, 4] ,beam_width=1)

tf.Tensor(
[[[  3.   5.  65.   0.]
  [  3.   5.  50.   0.]]

 [[  3.   5.  65.   0.]
  [  3.   5.   0. 100.]]

 [[  3.   5.  65.   0.]
  [  3. 500.  66.   5.]]

 [[  3.   5.  65.   0.]
  [  3.   5.  64.   2.]]], shape=(4, 2, 4), dtype=float32)


In [ ]:
y[0]

In [ ]:
tf.sparse.to_dense(y[0][0])

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[2, 0, 0],
       [2, 1, 2]])>

In [ ]:
y 

([<tensorflow.python.framework.sparse_tensor.SparseTensor at 0x7f07e416d1d0>],
 <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[5.9000906e-29],
        [0.0000000e+00]], dtype=float32)>)